//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDtl
    {
        public int PID { get; set; }
        public string BANKCODE { get; set; }
        public string CURRCODE { get; set; }
        public string SWIFTNO { get; set; }
        public string ROUTING { get; set; }
        public Nullable<bool> RDEL { get; set; }
    
        public virtual BankHdr BankHdr { get; set; }
    }
}
