//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyCat
    {
        public Nullable<int> PID { get; set; }
        public string CATEGORY { get; set; }
        public string CAT_CODE { get; set; }
        public Nullable<decimal> MARK_UP { get; set; }
    }
}
