//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartPly
    {
        public int PID { get; set; }
        public Nullable<int> CRTN_PLY { get; set; }
        public Nullable<decimal> RATEBROWN { get; set; }
        public Nullable<decimal> RATECOLOR { get; set; }
        public Nullable<bool> IPDEFAULT { get; set; }
        public Nullable<bool> MPDEFAULT { get; set; }
        public Nullable<decimal> BOARDWIDTH { get; set; }
        public Nullable<bool> INCH_CMS { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
