//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Warehousemasts = new HashSet<Warehousemast>();
        }
    
        public int PID { get; set; }
        public string CODE { get; set; }
        public string COMPANY1 { get; set; }
        public string COMP_ADD1 { get; set; }
        public string COMP_ADD2 { get; set; }
        public string COMP_ADD3 { get; set; }
        public string COMP_ADD4 { get; set; }
        public string COMP_ADD5 { get; set; }
        public string PHONE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string E_MAIL { get; set; }
        public string WEBSITE { get; set; }
        public string SWIFT_NO { get; set; }
        public string AUTH_SIGN { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ADD1 { get; set; }
        public string BANK_ADD2 { get; set; }
        public string BANK_ADD3 { get; set; }
        public string BANK_ADD4 { get; set; }
        public string BANK_TELEX { get; set; }
        public string DESG { get; set; }
        public string DIRECTOR { get; set; }
        public string RES_ADD1 { get; set; }
        public string RES_ADD2 { get; set; }
        public string OFF_ADD1 { get; set; }
        public string OFF_ADD2 { get; set; }
        public string IE_CODE { get; set; }
        public string RBI_CODE { get; set; }
        public string BANK_N1 { get; set; }
        public string BANK_N2 { get; set; }
        public string ACCOUNT { get; set; }
        public string LDGR_NO { get; set; }
        public string EXP_REF { get; set; }
        public string OTH_REF { get; set; }
        public string LOC_BANK_N { get; set; }
        public string LOC_BANKA1 { get; set; }
        public string LOC_B_ACCN { get; set; }
        public string LOC_B_LDGR { get; set; }
        public Nullable<decimal> PRO_NO { get; set; }
        public Nullable<decimal> PKL_NO { get; set; }
        public Nullable<decimal> INV_NO { get; set; }
        public Nullable<decimal> PO_NO { get; set; }
        public Nullable<decimal> RPO_NO { get; set; }
        public string PRO_PREFIX { get; set; }
        public string PKL_PREFIX { get; set; }
        public string PO_PREFIX { get; set; }
        public string LOGO { get; set; }
        public Nullable<System.DateTime> DT_ESTB { get; set; }
        public Nullable<System.DateTime> IEC_ISSDT { get; set; }
        public string IEC_ISSAUT { get; set; }
        public string IEC_BRANCH { get; set; }
        public string EXP_TYPE { get; set; }
        public Nullable<bool> EXP_TYPE1 { get; set; }
        public Nullable<bool> EXP_TYPE2 { get; set; }
        public Nullable<bool> EXP_TYPE3 { get; set; }
        public string PAN_NO { get; set; }
        public Nullable<System.DateTime> PAN_ISSDT { get; set; }
        public string PAN_AUTH { get; set; }
        public string SSI_NO_DT { get; set; }
        public string SSI_AUTH { get; set; }
        public string EHTH_NO { get; set; }
        public Nullable<System.DateTime> EHTH_DT { get; set; }
        public Nullable<System.DateTime> EHTH_UPTO { get; set; }
        public string EXP_NATURE { get; set; }
        public Nullable<bool> EXP_NATUR1 { get; set; }
        public Nullable<bool> EXP_NATUR2 { get; set; }
        public Nullable<bool> EXP_NATUR3 { get; set; }
        public Nullable<bool> EXP_NATUR4 { get; set; }
        public Nullable<bool> EXP_NATUR5 { get; set; }
        public string BK_NAME { get; set; }
        public string BK_ADD { get; set; }
        public string ACNT_TYPE { get; set; }
        public string BK_ACNO { get; set; }
        public Nullable<decimal> TOT_SALE { get; set; }
        public string DESIGNAT { get; set; }
        public string ANX1APLACE { get; set; }
        public string DNAME { get; set; }
        public string DFNAME { get; set; }
        public string DRESI_ADD { get; set; }
        public string DEMAIL { get; set; }
        public string DPHONE { get; set; }
        public string PLACE { get; set; }
        public string CONT_PER { get; set; }
        public string QUOTPREFIX { get; set; }
        public Nullable<bool> CACTIVE { get; set; }
        public string SIGN_PATH { get; set; }
        public Nullable<bool> PISIGN { get; set; }
        public Nullable<decimal> QUOTSTFR { get; set; }
        public Nullable<decimal> QUOTSTTO { get; set; }
        public string PLINE_PATH { get; set; }
        public string FPICT_PATH { get; set; }
        public string ABT_PGTXT { get; set; }
        public string HOME_PGTXT { get; set; }
        public string WEB_ADD { get; set; }
        public string BANK_ACC { get; set; }
        public Nullable<decimal> INITQUOTNO { get; set; }
        public string LSPREFIX { get; set; }
        public string RSPREFIX { get; set; }
        public string POHEAD1 { get; set; }
        public string POHEAD2 { get; set; }
        public string POHEAD3 { get; set; }
        public string POHEAD4 { get; set; }
        public string GST_ST_CD { get; set; }
        public string GSTIN_NO { get; set; }
        public string GSTPRIFIX { get; set; }
        public string GST_DEC1 { get; set; }
        public string GST_DEC2 { get; set; }
        public string GST_DEC3 { get; set; }
        public string GST_DEC4 { get; set; }
        public string GST_DEC5 { get; set; }
        public string GST_DEC6 { get; set; }
        public Nullable<int> GST_NDICL { get; set; }
        public string OTH_REF1 { get; set; }
        public string CIN_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehousemast> Warehousemasts { get; set; }
    }
}
