//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrMast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrMast()
        {
            this.ItemMasters = new HashSet<ItemMaster>();
        }
    
        public int PID { get; set; }
        public string CURR_CODE { get; set; }
        public string CURR_NAME { get; set; }
        public Nullable<decimal> CURR_CONV { get; set; }
        public Nullable<decimal> EXC_RATE { get; set; }
        public string COIN { get; set; }
        public string CURR_SEP { get; set; }
        public Nullable<bool> DECI_RQD { get; set; }
        public string USER_CODE { get; set; }
        public string CURR_CAP { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMaster> ItemMasters { get; set; }
    }
}
