//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyMast
    {
        public Nullable<int> PID { get; set; }
        public string PURC_GRP { get; set; }
        public string CODE { get; set; }
        public string DESC_1 { get; set; }
        public string DESC_2 { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string HSTUS { get; set; }
        public string HSN_SAC { get; set; }
        public Nullable<bool> GSPFREE { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
