//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Mast
    {
        public int PID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string PANTONECODE { get; set; }
        public string NEELAMCODE { get; set; }
        public string PPREFIX { get; set; }
        public string CSHADEPATH { get; set; }
        public Nullable<bool> LINKDLINK { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
