//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GstMast
    {
        public Nullable<int> PID { get; set; }
        public string VAT_CODE { get; set; }
        public string DESCRIPTIO { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<bool> TAX_EXMPT { get; set; }
        public Nullable<bool> SALES_GST { get; set; }
        public Nullable<decimal> CGST_RATE { get; set; }
        public Nullable<decimal> SGST_RATE { get; set; }
        public Nullable<decimal> UTGST_RATE { get; set; }
        public Nullable<decimal> IGST_RATE { get; set; }
        public Nullable<int> GST_TYPE { get; set; }
        public Nullable<decimal> TAX_RATE { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
