//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisPrty
    {
        public int PID { get; set; }
        public string CODE { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string CONTPER { get; set; }
        public string EMAIL { get; set; }
        public string WEB_ADD { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> RELA { get; set; }
        public string REMARKS { get; set; }
        public string MISCTYPE { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
