//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules31012018
    {
        public int PID { get; set; }
        public string Grp_Code { get; set; }
        public string Grp_Desc { get; set; }
        public string Mod_Code { get; set; }
        public string Menu_Desc { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> OrdKeyMain { get; set; }
        public Nullable<int> OrdKeyChd { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Action { get; set; }
        public string Menu__Icon { get; set; }
        public string Grp_Icon { get; set; }
    }
}
