//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyType
    {
        public int Pid { get; set; }
        public string Party_Description { get; set; }
        public string Type { get; set; }
    }
}
