//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTerm
    {
        public Nullable<int> PID { get; set; }
        public string CODE { get; set; }
        public string TERM1 { get; set; }
        public string TERM2 { get; set; }
        public string TERM3 { get; set; }
        public string TERM4 { get; set; }
        public string TERM5 { get; set; }
        public string TERM6 { get; set; }
        public string TERM7 { get; set; }
        public string TERM8 { get; set; }
        public Nullable<bool> TRANREM { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
