//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuMast
    {
        public int PID { get; set; }
        public string BUY_VND { get; set; }
        public string ITEM_CODE { get; set; }
        public string BUYER_CODE { get; set; }
        public string SKU_NO { get; set; }
        public string ITCHSTMP { get; set; }
        public string ITEM_NAME1 { get; set; }
        public string ITEM_NAME2 { get; set; }
        public string ITEM_NAME3 { get; set; }
        public string ITEM_NAME4 { get; set; }
        public string CNFTYP { get; set; }
        public string CURR { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<decimal> EXC_RATE { get; set; }
        public Nullable<decimal> SALE_RATE { get; set; }
        public string SALE_CURR { get; set; }
        public Nullable<System.DateTime> SALE_DATE { get; set; }
        public Nullable<bool> INCH_CMS { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> ITM_LENGTH { get; set; }
        public Nullable<decimal> ITM_BRDTH { get; set; }
        public Nullable<decimal> ITM_HEIGHT { get; set; }
        public Nullable<decimal> NET_WT { get; set; }
        public string EAN_NO { get; set; }
        public Nullable<decimal> IN_CRTNPCS { get; set; }
        public Nullable<decimal> IN_CRTNLEN { get; set; }
        public Nullable<decimal> IN_CRTNBRD { get; set; }
        public Nullable<decimal> IN_CRTNHT { get; set; }
        public Nullable<decimal> INCRNET_WT { get; set; }
        public Nullable<decimal> INRCRT_CBM { get; set; }
        public string IEAN_NO { get; set; }
        public Nullable<decimal> PRCRTN_QTY { get; set; }
        public Nullable<decimal> CRTNLENGTH { get; set; }
        public Nullable<decimal> CRTNBRDTH { get; set; }
        public Nullable<decimal> CRTNHEIGHT { get; set; }
        public Nullable<decimal> CRTN_CBM { get; set; }
        public Nullable<decimal> MCNET_WT { get; set; }
        public Nullable<decimal> MCGROSWT { get; set; }
        public string MEAN_NO { get; set; }
        public string SIZE_CODE { get; set; }
        public string FINCODE { get; set; }
        public string TARRIF { get; set; }
        public string PACK_INS { get; set; }
        public string LBL_INS { get; set; }
        public string OTH_INS { get; set; }
        public string VND_DTL1 { get; set; }
        public string VND_DTL2 { get; set; }
        public string REMARKS { get; set; }
        public string ITMLBLPATH { get; set; }
        public string CASLBLPATH { get; set; }
        public string BRNLBLPATH { get; set; }
        public string INPUT_BY { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
    }
}
