//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int PID { get; set; }
        public string User_Code { get; set; }
        public string Mod_Code { get; set; }
        public Nullable<bool> AddNew { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Print { get; set; }
        public Nullable<bool> Assign { get; set; }
        public string SubMenu { get; set; }
    }
}
