//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboERP_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usergroup
    {
        public int Pid { get; set; }
        public string Usergroup_Code { get; set; }
        public string Usergrp_Name { get; set; }
        public string Input_By { get; set; }
        public Nullable<System.DateTime> Input_Dt { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dt { get; set; }
        public Nullable<int> User_Role { get; set; }
    }
}
