export class SkuMastModel
{
  public PID:number
  public BUY_VND:string
  public ITEM_CODE:string
  public BUYER_CODE:string
  public SKU_NO:string
  public ITCHSTMP:string
  public ITEM_NAME1:string
  public ITEM_NAME2:string
  public ITEM_NAME3:string
  public ITEM_NAME4:string
  public CNFTYP:string
  public CURR:string
  public RATE:number
  public FOB:number
  public EXC_RATE:number
  public SALE_RATE
  public SALE_CURR:string
  public SALE_DATE:Date
  public INCH_CMS:boolean
  public UNIT:string
  public ITM_LENGTH:number
  public ITM_BRDTH:number
  public ITM_HEIGHT:number
  public NET_WT:number
  public EAN_NO:string
  public IN_CRTNPCS:number
  public IN_CRTNLEN:number
  public IN_CRTNBRD:number
  public IN_CRTNHT:number
  public INCRNET_WT:number
  public INRCRT_CBM:number
  public IEAN_NO:string
  public PRCRTN_QTY:number
  public CRTNLENGTH:number
  public CRTNBRDTH:number
  public CRTNHEIGHT:number
  public CRTN_CBM:number
  public MCNET_WT:number
  public MCGROSWT:number
  public MEAN_NO:string
  public SIZE_CODE:string
  public FINCODE:string
  public TARRIF:string
  public PACK_INS:string
  public LBL_INS:string
  public OTH_INS:string
  public VND_DTL1:string
  public VND_DTL2:string
  public REMARKS:string
  public ITMLBLPATH:string
  public CASLBLPATH:string
  public BRNLBLPATH:string
}